### ISSUE TITLE
Convert it to list 

### ISSUE THREAD

**Issue by yumegel2** [karlaizq/mywebclass-agile-docs#1]
Make sure they are a list instead of just one sentence.

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/DevOps%20Implementation%20for%20MyWebClass#L28-L30

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/Basic%20Project%20Documentation%20and%20Project%20Management#L25-L27

**Comment by karlaizq** [comment]
Corrections have been made
