### ISSUE TITLE
Convert to Markdown file

### ISSUE THREAD

**Issue by yumegel2** [karlaizq/mywebclass-agile-docs#2]
The files below are not Markdown files. To change them: make sure the new document file name has no spaces (so use _ as a substitute) and make sure the end in .md

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/base%20website%20template

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/Basic%20Project%20Documentation%20and%20Project%20Management

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/DevOps%20Implementation%20for%20MyWebClass

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/EPIC/DevOps%20Implementation%20for%20MyWebClass

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/EPIC/MyWebClass%20Project%20Planning%20and%20Management

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/EPIC/MyWebClass.org%20Website%20Template%20Development

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/EPIC/stories/story_1

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/EPIC/stories/story_2

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/EPIC/stories/story_3

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/EPIC/stories/tasks/task_1

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/EPIC/stories/tasks/task_2

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/EPIC/stories/tasks/task_3

**Comment by karlaizq** [comment]
files extensions have been set
