### ISSUE TITLE
Reduce initiatives

### ISSUE THREAD

**Issue by yumegel2** [karlaizq/mywebclass-agile-docs#5]
It looks like you have 5 initiatives despite only having 3 so delete the files below:

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/initiative_basic_webpage_template.md

https://github.com/karlaizq/mywebclass-agile-docs/blob/cff29549b010363163b98d038d5065398f415cee/documentation/theme_1/initiatives/initiative_devops.md

**Comment by karlaizq** [comment]
Deleted 2 extra files
